name: Deploy Next.js Static Site

on:
  push:
    branches:
      - dev  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.12.2"  

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js Project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git worktree add -f gh-pages out
          cd gh-pages
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:gh-pages

      # - name: Deploy to GitHub Pages
      #   if: ${{ github.ref == 'refs/heads/dev' }}
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./out  # The output directory

      # - name: Clear GitHub Pages Cache
      #   run: |
      #     git config --global user.name "${{ github.actor }}"
      #     git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      #     git checkout --orphan temp_branch
      #     git add -A
      #     git commit -m "Clearing cache for new deployment"
      #     git push --force origin temp_branch
      #     git push --delete origin temp_branch
